<?php
/**
 * ProgramsReviewTypesReviewsImagesApi
 * PHP version 5
 *
 * @category Class
 * @package  Softonic\CatalogApiSdk
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Catalog API
 *
 * API that allows to manage the programs catalog of Softonic
 *
 * OpenAPI spec version: 2.39.0
 * Contact: team.platform@softonic.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Softonic\CatalogApiSdk\Client\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Softonic\CatalogApiSdk\ApiException;
use Softonic\CatalogApiSdk\Configuration;
use Softonic\CatalogApiSdk\HeaderSelector;
use Softonic\CatalogApiSdk\ObjectSerializer;

/**
 * ProgramsReviewTypesReviewsImagesApi Class Doc Comment
 *
 * @category Class
 * @package  Softonic\CatalogApiSdk
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ProgramsReviewTypesReviewsImagesApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation createProgramReviewTypeReviewImage
     *
     * Creates a new ProgramReviewTypeReviewImage
     *
     * @param  string $id_program Program UUID (required)
     * @param  string $id_review_type Review owner type (required)
     * @param  string $id_review Review identifier as UUID (required)
     * @param  \Softonic\CatalogApiSdk\Client\Model\ProgramReviewTypeReviewImage $body body (optional)
     *
     * @throws \Softonic\CatalogApiSdk\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return void
     */
    public function createProgramReviewTypeReviewImage($id_program, $id_review_type, $id_review, $body = null)
    {
        $this->createProgramReviewTypeReviewImageWithHttpInfo($id_program, $id_review_type, $id_review, $body);
    }

    /**
     * Operation createProgramReviewTypeReviewImageWithHttpInfo
     *
     * Creates a new ProgramReviewTypeReviewImage
     *
     * @param  string $id_program Program UUID (required)
     * @param  string $id_review_type Review owner type (required)
     * @param  string $id_review Review identifier as UUID (required)
     * @param  \Softonic\CatalogApiSdk\Client\Model\ProgramReviewTypeReviewImage $body (optional)
     *
     * @throws \Softonic\CatalogApiSdk\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function createProgramReviewTypeReviewImageWithHttpInfo($id_program, $id_review_type, $id_review, $body = null)
    {
        $returnType = '';
        $request = $this->createProgramReviewTypeReviewImageRequest($id_program, $id_review_type, $id_review, $body);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
            throw $e;
        }
    }

    /**
     * Operation createProgramReviewTypeReviewImageAsync
     *
     * Creates a new ProgramReviewTypeReviewImage
     *
     * @param  string $id_program Program UUID (required)
     * @param  string $id_review_type Review owner type (required)
     * @param  string $id_review Review identifier as UUID (required)
     * @param  \Softonic\CatalogApiSdk\Client\Model\ProgramReviewTypeReviewImage $body (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createProgramReviewTypeReviewImageAsync($id_program, $id_review_type, $id_review, $body = null)
    {
        return $this->createProgramReviewTypeReviewImageAsyncWithHttpInfo($id_program, $id_review_type, $id_review, $body)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation createProgramReviewTypeReviewImageAsyncWithHttpInfo
     *
     * Creates a new ProgramReviewTypeReviewImage
     *
     * @param  string $id_program Program UUID (required)
     * @param  string $id_review_type Review owner type (required)
     * @param  string $id_review Review identifier as UUID (required)
     * @param  \Softonic\CatalogApiSdk\Client\Model\ProgramReviewTypeReviewImage $body (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createProgramReviewTypeReviewImageAsyncWithHttpInfo($id_program, $id_review_type, $id_review, $body = null)
    {
        $returnType = '';
        $request = $this->createProgramReviewTypeReviewImageRequest($id_program, $id_review_type, $id_review, $body);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'createProgramReviewTypeReviewImage'
     *
     * @param  string $id_program Program UUID (required)
     * @param  string $id_review_type Review owner type (required)
     * @param  string $id_review Review identifier as UUID (required)
     * @param  \Softonic\CatalogApiSdk\Client\Model\ProgramReviewTypeReviewImage $body (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function createProgramReviewTypeReviewImageRequest($id_program, $id_review_type, $id_review, $body = null)
    {
        // verify the required parameter 'id_program' is set
        if ($id_program === null) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id_program when calling createProgramReviewTypeReviewImage'
            );
        }
        if (strlen($id_program) > 36) {
            throw new \InvalidArgumentException('invalid length for "$id_program" when calling ProgramsReviewTypesReviewsImagesApi.createProgramReviewTypeReviewImage, must be smaller than or equal to 36.');
        }
        if (strlen($id_program) < 36) {
            throw new \InvalidArgumentException('invalid length for "$id_program" when calling ProgramsReviewTypesReviewsImagesApi.createProgramReviewTypeReviewImage, must be bigger than or equal to 36.');
        }

        // verify the required parameter 'id_review_type' is set
        if ($id_review_type === null) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id_review_type when calling createProgramReviewTypeReviewImage'
            );
        }
        // verify the required parameter 'id_review' is set
        if ($id_review === null) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id_review when calling createProgramReviewTypeReviewImage'
            );
        }
        if (strlen($id_review) > 36) {
            throw new \InvalidArgumentException('invalid length for "$id_review" when calling ProgramsReviewTypesReviewsImagesApi.createProgramReviewTypeReviewImage, must be smaller than or equal to 36.');
        }
        if (strlen($id_review) < 36) {
            throw new \InvalidArgumentException('invalid length for "$id_review" when calling ProgramsReviewTypesReviewsImagesApi.createProgramReviewTypeReviewImage, must be bigger than or equal to 36.');
        }


        $resourcePath = '/programs/{id_program}/review-types/{id_review_type}/reviews/{id_review}/images';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // path params
        if ($id_program !== null) {
            $resourcePath = str_replace(
                '{' . 'id_program' . '}',
                ObjectSerializer::toPathValue($id_program),
                $resourcePath
            );
        }
        // path params
        if ($id_review_type !== null) {
            $resourcePath = str_replace(
                '{' . 'id_review_type' . '}',
                ObjectSerializer::toPathValue($id_review_type),
                $resourcePath
            );
        }
        // path params
        if ($id_review !== null) {
            $resourcePath = str_replace(
                '{' . 'id_review' . '}',
                ObjectSerializer::toPathValue($id_review),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;
        if (isset($body)) {
            $_tempBody = $body;
        }

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }
        // this endpoint requires OAuth (access token)
        if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }
        // this endpoint requires OAuth (access token)
        if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }
        // this endpoint requires OAuth (access token)
        if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation deleteProgramReviewTypeReviewImage
     *
     * Deletes a ProgramReviewTypeReviewImage
     *
     * @param  string $id_program Program UUID (required)
     * @param  string $id_review_type Review owner type (required)
     * @param  string $id_review Review identifier as UUID (required)
     * @param  string $id_image Image identifier in SHA1-Hash format derived from path (required)
     *
     * @throws \Softonic\CatalogApiSdk\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return void
     */
    public function deleteProgramReviewTypeReviewImage($id_program, $id_review_type, $id_review, $id_image)
    {
        $this->deleteProgramReviewTypeReviewImageWithHttpInfo($id_program, $id_review_type, $id_review, $id_image);
    }

    /**
     * Operation deleteProgramReviewTypeReviewImageWithHttpInfo
     *
     * Deletes a ProgramReviewTypeReviewImage
     *
     * @param  string $id_program Program UUID (required)
     * @param  string $id_review_type Review owner type (required)
     * @param  string $id_review Review identifier as UUID (required)
     * @param  string $id_image Image identifier in SHA1-Hash format derived from path (required)
     *
     * @throws \Softonic\CatalogApiSdk\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function deleteProgramReviewTypeReviewImageWithHttpInfo($id_program, $id_review_type, $id_review, $id_image)
    {
        $returnType = '';
        $request = $this->deleteProgramReviewTypeReviewImageRequest($id_program, $id_review_type, $id_review, $id_image);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
            throw $e;
        }
    }

    /**
     * Operation deleteProgramReviewTypeReviewImageAsync
     *
     * Deletes a ProgramReviewTypeReviewImage
     *
     * @param  string $id_program Program UUID (required)
     * @param  string $id_review_type Review owner type (required)
     * @param  string $id_review Review identifier as UUID (required)
     * @param  string $id_image Image identifier in SHA1-Hash format derived from path (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function deleteProgramReviewTypeReviewImageAsync($id_program, $id_review_type, $id_review, $id_image)
    {
        return $this->deleteProgramReviewTypeReviewImageAsyncWithHttpInfo($id_program, $id_review_type, $id_review, $id_image)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation deleteProgramReviewTypeReviewImageAsyncWithHttpInfo
     *
     * Deletes a ProgramReviewTypeReviewImage
     *
     * @param  string $id_program Program UUID (required)
     * @param  string $id_review_type Review owner type (required)
     * @param  string $id_review Review identifier as UUID (required)
     * @param  string $id_image Image identifier in SHA1-Hash format derived from path (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function deleteProgramReviewTypeReviewImageAsyncWithHttpInfo($id_program, $id_review_type, $id_review, $id_image)
    {
        $returnType = '';
        $request = $this->deleteProgramReviewTypeReviewImageRequest($id_program, $id_review_type, $id_review, $id_image);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'deleteProgramReviewTypeReviewImage'
     *
     * @param  string $id_program Program UUID (required)
     * @param  string $id_review_type Review owner type (required)
     * @param  string $id_review Review identifier as UUID (required)
     * @param  string $id_image Image identifier in SHA1-Hash format derived from path (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function deleteProgramReviewTypeReviewImageRequest($id_program, $id_review_type, $id_review, $id_image)
    {
        // verify the required parameter 'id_program' is set
        if ($id_program === null) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id_program when calling deleteProgramReviewTypeReviewImage'
            );
        }
        if (strlen($id_program) > 36) {
            throw new \InvalidArgumentException('invalid length for "$id_program" when calling ProgramsReviewTypesReviewsImagesApi.deleteProgramReviewTypeReviewImage, must be smaller than or equal to 36.');
        }
        if (strlen($id_program) < 36) {
            throw new \InvalidArgumentException('invalid length for "$id_program" when calling ProgramsReviewTypesReviewsImagesApi.deleteProgramReviewTypeReviewImage, must be bigger than or equal to 36.');
        }

        // verify the required parameter 'id_review_type' is set
        if ($id_review_type === null) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id_review_type when calling deleteProgramReviewTypeReviewImage'
            );
        }
        // verify the required parameter 'id_review' is set
        if ($id_review === null) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id_review when calling deleteProgramReviewTypeReviewImage'
            );
        }
        if (strlen($id_review) > 36) {
            throw new \InvalidArgumentException('invalid length for "$id_review" when calling ProgramsReviewTypesReviewsImagesApi.deleteProgramReviewTypeReviewImage, must be smaller than or equal to 36.');
        }
        if (strlen($id_review) < 36) {
            throw new \InvalidArgumentException('invalid length for "$id_review" when calling ProgramsReviewTypesReviewsImagesApi.deleteProgramReviewTypeReviewImage, must be bigger than or equal to 36.');
        }

        // verify the required parameter 'id_image' is set
        if ($id_image === null) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id_image when calling deleteProgramReviewTypeReviewImage'
            );
        }
        if (strlen($id_image) > 40) {
            throw new \InvalidArgumentException('invalid length for "$id_image" when calling ProgramsReviewTypesReviewsImagesApi.deleteProgramReviewTypeReviewImage, must be smaller than or equal to 40.');
        }
        if (strlen($id_image) < 40) {
            throw new \InvalidArgumentException('invalid length for "$id_image" when calling ProgramsReviewTypesReviewsImagesApi.deleteProgramReviewTypeReviewImage, must be bigger than or equal to 40.');
        }


        $resourcePath = '/programs/{id_program}/review-types/{id_review_type}/reviews/{id_review}/images/{id_image}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // path params
        if ($id_program !== null) {
            $resourcePath = str_replace(
                '{' . 'id_program' . '}',
                ObjectSerializer::toPathValue($id_program),
                $resourcePath
            );
        }
        // path params
        if ($id_review_type !== null) {
            $resourcePath = str_replace(
                '{' . 'id_review_type' . '}',
                ObjectSerializer::toPathValue($id_review_type),
                $resourcePath
            );
        }
        // path params
        if ($id_review !== null) {
            $resourcePath = str_replace(
                '{' . 'id_review' . '}',
                ObjectSerializer::toPathValue($id_review),
                $resourcePath
            );
        }
        // path params
        if ($id_image !== null) {
            $resourcePath = str_replace(
                '{' . 'id_image' . '}',
                ObjectSerializer::toPathValue($id_image),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }
        // this endpoint requires OAuth (access token)
        if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }
        // this endpoint requires OAuth (access token)
        if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }
        // this endpoint requires OAuth (access token)
        if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'DELETE',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation findProgramReviewTypeReviewImage
     *
     * List of ProgramReviewTypeReviewImages
     *
     * @param  string $id_program Program UUID (required)
     * @param  string $id_review_type Review owner type (required)
     * @param  string $id_review Review identifier as UUID (required)
     *
     * @throws \Softonic\CatalogApiSdk\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Softonic\CatalogApiSdk\Client\Model\ProgramReviewTypeReviewImage[]
     */
    public function findProgramReviewTypeReviewImage($id_program, $id_review_type, $id_review)
    {
        list($response) = $this->findProgramReviewTypeReviewImageWithHttpInfo($id_program, $id_review_type, $id_review);
        return $response;
    }

    /**
     * Operation findProgramReviewTypeReviewImageWithHttpInfo
     *
     * List of ProgramReviewTypeReviewImages
     *
     * @param  string $id_program Program UUID (required)
     * @param  string $id_review_type Review owner type (required)
     * @param  string $id_review Review identifier as UUID (required)
     *
     * @throws \Softonic\CatalogApiSdk\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Softonic\CatalogApiSdk\Client\Model\ProgramReviewTypeReviewImage[], HTTP status code, HTTP response headers (array of strings)
     */
    public function findProgramReviewTypeReviewImageWithHttpInfo($id_program, $id_review_type, $id_review)
    {
        $returnType = '\Softonic\CatalogApiSdk\Client\Model\ProgramReviewTypeReviewImage[]';
        $request = $this->findProgramReviewTypeReviewImageRequest($id_program, $id_review_type, $id_review);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Softonic\CatalogApiSdk\Client\Model\ProgramReviewTypeReviewImage[]',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation findProgramReviewTypeReviewImageAsync
     *
     * List of ProgramReviewTypeReviewImages
     *
     * @param  string $id_program Program UUID (required)
     * @param  string $id_review_type Review owner type (required)
     * @param  string $id_review Review identifier as UUID (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function findProgramReviewTypeReviewImageAsync($id_program, $id_review_type, $id_review)
    {
        return $this->findProgramReviewTypeReviewImageAsyncWithHttpInfo($id_program, $id_review_type, $id_review)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation findProgramReviewTypeReviewImageAsyncWithHttpInfo
     *
     * List of ProgramReviewTypeReviewImages
     *
     * @param  string $id_program Program UUID (required)
     * @param  string $id_review_type Review owner type (required)
     * @param  string $id_review Review identifier as UUID (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function findProgramReviewTypeReviewImageAsyncWithHttpInfo($id_program, $id_review_type, $id_review)
    {
        $returnType = '\Softonic\CatalogApiSdk\Client\Model\ProgramReviewTypeReviewImage[]';
        $request = $this->findProgramReviewTypeReviewImageRequest($id_program, $id_review_type, $id_review);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'findProgramReviewTypeReviewImage'
     *
     * @param  string $id_program Program UUID (required)
     * @param  string $id_review_type Review owner type (required)
     * @param  string $id_review Review identifier as UUID (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function findProgramReviewTypeReviewImageRequest($id_program, $id_review_type, $id_review)
    {
        // verify the required parameter 'id_program' is set
        if ($id_program === null) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id_program when calling findProgramReviewTypeReviewImage'
            );
        }
        if (strlen($id_program) > 36) {
            throw new \InvalidArgumentException('invalid length for "$id_program" when calling ProgramsReviewTypesReviewsImagesApi.findProgramReviewTypeReviewImage, must be smaller than or equal to 36.');
        }
        if (strlen($id_program) < 36) {
            throw new \InvalidArgumentException('invalid length for "$id_program" when calling ProgramsReviewTypesReviewsImagesApi.findProgramReviewTypeReviewImage, must be bigger than or equal to 36.');
        }

        // verify the required parameter 'id_review_type' is set
        if ($id_review_type === null) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id_review_type when calling findProgramReviewTypeReviewImage'
            );
        }
        // verify the required parameter 'id_review' is set
        if ($id_review === null) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id_review when calling findProgramReviewTypeReviewImage'
            );
        }
        if (strlen($id_review) > 36) {
            throw new \InvalidArgumentException('invalid length for "$id_review" when calling ProgramsReviewTypesReviewsImagesApi.findProgramReviewTypeReviewImage, must be smaller than or equal to 36.');
        }
        if (strlen($id_review) < 36) {
            throw new \InvalidArgumentException('invalid length for "$id_review" when calling ProgramsReviewTypesReviewsImagesApi.findProgramReviewTypeReviewImage, must be bigger than or equal to 36.');
        }


        $resourcePath = '/programs/{id_program}/review-types/{id_review_type}/reviews/{id_review}/images';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // path params
        if ($id_program !== null) {
            $resourcePath = str_replace(
                '{' . 'id_program' . '}',
                ObjectSerializer::toPathValue($id_program),
                $resourcePath
            );
        }
        // path params
        if ($id_review_type !== null) {
            $resourcePath = str_replace(
                '{' . 'id_review_type' . '}',
                ObjectSerializer::toPathValue($id_review_type),
                $resourcePath
            );
        }
        // path params
        if ($id_review !== null) {
            $resourcePath = str_replace(
                '{' . 'id_review' . '}',
                ObjectSerializer::toPathValue($id_review),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }
        // this endpoint requires OAuth (access token)
        if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }
        // this endpoint requires OAuth (access token)
        if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }
        // this endpoint requires OAuth (access token)
        if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation readProgramReviewTypeReviewImage
     *
     * Fetches a single ProgramReviewTypeReviewImage
     *
     * @param  string $id_program Program UUID (required)
     * @param  string $id_review_type Review owner type (required)
     * @param  string $id_review Review identifier as UUID (required)
     * @param  string $id_image Image identifier in SHA1-Hash format derived from path (required)
     *
     * @throws \Softonic\CatalogApiSdk\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Softonic\CatalogApiSdk\Client\Model\ProgramReviewTypeReviewImage
     */
    public function readProgramReviewTypeReviewImage($id_program, $id_review_type, $id_review, $id_image)
    {
        list($response) = $this->readProgramReviewTypeReviewImageWithHttpInfo($id_program, $id_review_type, $id_review, $id_image);
        return $response;
    }

    /**
     * Operation readProgramReviewTypeReviewImageWithHttpInfo
     *
     * Fetches a single ProgramReviewTypeReviewImage
     *
     * @param  string $id_program Program UUID (required)
     * @param  string $id_review_type Review owner type (required)
     * @param  string $id_review Review identifier as UUID (required)
     * @param  string $id_image Image identifier in SHA1-Hash format derived from path (required)
     *
     * @throws \Softonic\CatalogApiSdk\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Softonic\CatalogApiSdk\Client\Model\ProgramReviewTypeReviewImage, HTTP status code, HTTP response headers (array of strings)
     */
    public function readProgramReviewTypeReviewImageWithHttpInfo($id_program, $id_review_type, $id_review, $id_image)
    {
        $returnType = '\Softonic\CatalogApiSdk\Client\Model\ProgramReviewTypeReviewImage';
        $request = $this->readProgramReviewTypeReviewImageRequest($id_program, $id_review_type, $id_review, $id_image);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Softonic\CatalogApiSdk\Client\Model\ProgramReviewTypeReviewImage',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation readProgramReviewTypeReviewImageAsync
     *
     * Fetches a single ProgramReviewTypeReviewImage
     *
     * @param  string $id_program Program UUID (required)
     * @param  string $id_review_type Review owner type (required)
     * @param  string $id_review Review identifier as UUID (required)
     * @param  string $id_image Image identifier in SHA1-Hash format derived from path (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function readProgramReviewTypeReviewImageAsync($id_program, $id_review_type, $id_review, $id_image)
    {
        return $this->readProgramReviewTypeReviewImageAsyncWithHttpInfo($id_program, $id_review_type, $id_review, $id_image)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation readProgramReviewTypeReviewImageAsyncWithHttpInfo
     *
     * Fetches a single ProgramReviewTypeReviewImage
     *
     * @param  string $id_program Program UUID (required)
     * @param  string $id_review_type Review owner type (required)
     * @param  string $id_review Review identifier as UUID (required)
     * @param  string $id_image Image identifier in SHA1-Hash format derived from path (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function readProgramReviewTypeReviewImageAsyncWithHttpInfo($id_program, $id_review_type, $id_review, $id_image)
    {
        $returnType = '\Softonic\CatalogApiSdk\Client\Model\ProgramReviewTypeReviewImage';
        $request = $this->readProgramReviewTypeReviewImageRequest($id_program, $id_review_type, $id_review, $id_image);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'readProgramReviewTypeReviewImage'
     *
     * @param  string $id_program Program UUID (required)
     * @param  string $id_review_type Review owner type (required)
     * @param  string $id_review Review identifier as UUID (required)
     * @param  string $id_image Image identifier in SHA1-Hash format derived from path (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function readProgramReviewTypeReviewImageRequest($id_program, $id_review_type, $id_review, $id_image)
    {
        // verify the required parameter 'id_program' is set
        if ($id_program === null) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id_program when calling readProgramReviewTypeReviewImage'
            );
        }
        if (strlen($id_program) > 36) {
            throw new \InvalidArgumentException('invalid length for "$id_program" when calling ProgramsReviewTypesReviewsImagesApi.readProgramReviewTypeReviewImage, must be smaller than or equal to 36.');
        }
        if (strlen($id_program) < 36) {
            throw new \InvalidArgumentException('invalid length for "$id_program" when calling ProgramsReviewTypesReviewsImagesApi.readProgramReviewTypeReviewImage, must be bigger than or equal to 36.');
        }

        // verify the required parameter 'id_review_type' is set
        if ($id_review_type === null) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id_review_type when calling readProgramReviewTypeReviewImage'
            );
        }
        // verify the required parameter 'id_review' is set
        if ($id_review === null) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id_review when calling readProgramReviewTypeReviewImage'
            );
        }
        if (strlen($id_review) > 36) {
            throw new \InvalidArgumentException('invalid length for "$id_review" when calling ProgramsReviewTypesReviewsImagesApi.readProgramReviewTypeReviewImage, must be smaller than or equal to 36.');
        }
        if (strlen($id_review) < 36) {
            throw new \InvalidArgumentException('invalid length for "$id_review" when calling ProgramsReviewTypesReviewsImagesApi.readProgramReviewTypeReviewImage, must be bigger than or equal to 36.');
        }

        // verify the required parameter 'id_image' is set
        if ($id_image === null) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id_image when calling readProgramReviewTypeReviewImage'
            );
        }
        if (strlen($id_image) > 40) {
            throw new \InvalidArgumentException('invalid length for "$id_image" when calling ProgramsReviewTypesReviewsImagesApi.readProgramReviewTypeReviewImage, must be smaller than or equal to 40.');
        }
        if (strlen($id_image) < 40) {
            throw new \InvalidArgumentException('invalid length for "$id_image" when calling ProgramsReviewTypesReviewsImagesApi.readProgramReviewTypeReviewImage, must be bigger than or equal to 40.');
        }


        $resourcePath = '/programs/{id_program}/review-types/{id_review_type}/reviews/{id_review}/images/{id_image}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // path params
        if ($id_program !== null) {
            $resourcePath = str_replace(
                '{' . 'id_program' . '}',
                ObjectSerializer::toPathValue($id_program),
                $resourcePath
            );
        }
        // path params
        if ($id_review_type !== null) {
            $resourcePath = str_replace(
                '{' . 'id_review_type' . '}',
                ObjectSerializer::toPathValue($id_review_type),
                $resourcePath
            );
        }
        // path params
        if ($id_review !== null) {
            $resourcePath = str_replace(
                '{' . 'id_review' . '}',
                ObjectSerializer::toPathValue($id_review),
                $resourcePath
            );
        }
        // path params
        if ($id_image !== null) {
            $resourcePath = str_replace(
                '{' . 'id_image' . '}',
                ObjectSerializer::toPathValue($id_image),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }
        // this endpoint requires OAuth (access token)
        if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }
        // this endpoint requires OAuth (access token)
        if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }
        // this endpoint requires OAuth (access token)
        if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation replaceProgramReviewTypeReviewImage
     *
     * Entirely replaces a ProgramReviewTypeReviewImage
     *
     * @param  string $id_program Program UUID (required)
     * @param  string $id_review_type Review owner type (required)
     * @param  string $id_review Review identifier as UUID (required)
     * @param  string $id_image Image identifier in SHA1-Hash format derived from path (required)
     * @param  \Softonic\CatalogApiSdk\Client\Model\ProgramReviewTypeReviewImage $body body (optional)
     *
     * @throws \Softonic\CatalogApiSdk\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return void
     */
    public function replaceProgramReviewTypeReviewImage($id_program, $id_review_type, $id_review, $id_image, $body = null)
    {
        $this->replaceProgramReviewTypeReviewImageWithHttpInfo($id_program, $id_review_type, $id_review, $id_image, $body);
    }

    /**
     * Operation replaceProgramReviewTypeReviewImageWithHttpInfo
     *
     * Entirely replaces a ProgramReviewTypeReviewImage
     *
     * @param  string $id_program Program UUID (required)
     * @param  string $id_review_type Review owner type (required)
     * @param  string $id_review Review identifier as UUID (required)
     * @param  string $id_image Image identifier in SHA1-Hash format derived from path (required)
     * @param  \Softonic\CatalogApiSdk\Client\Model\ProgramReviewTypeReviewImage $body (optional)
     *
     * @throws \Softonic\CatalogApiSdk\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function replaceProgramReviewTypeReviewImageWithHttpInfo($id_program, $id_review_type, $id_review, $id_image, $body = null)
    {
        $returnType = '';
        $request = $this->replaceProgramReviewTypeReviewImageRequest($id_program, $id_review_type, $id_review, $id_image, $body);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
            throw $e;
        }
    }

    /**
     * Operation replaceProgramReviewTypeReviewImageAsync
     *
     * Entirely replaces a ProgramReviewTypeReviewImage
     *
     * @param  string $id_program Program UUID (required)
     * @param  string $id_review_type Review owner type (required)
     * @param  string $id_review Review identifier as UUID (required)
     * @param  string $id_image Image identifier in SHA1-Hash format derived from path (required)
     * @param  \Softonic\CatalogApiSdk\Client\Model\ProgramReviewTypeReviewImage $body (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function replaceProgramReviewTypeReviewImageAsync($id_program, $id_review_type, $id_review, $id_image, $body = null)
    {
        return $this->replaceProgramReviewTypeReviewImageAsyncWithHttpInfo($id_program, $id_review_type, $id_review, $id_image, $body)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation replaceProgramReviewTypeReviewImageAsyncWithHttpInfo
     *
     * Entirely replaces a ProgramReviewTypeReviewImage
     *
     * @param  string $id_program Program UUID (required)
     * @param  string $id_review_type Review owner type (required)
     * @param  string $id_review Review identifier as UUID (required)
     * @param  string $id_image Image identifier in SHA1-Hash format derived from path (required)
     * @param  \Softonic\CatalogApiSdk\Client\Model\ProgramReviewTypeReviewImage $body (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function replaceProgramReviewTypeReviewImageAsyncWithHttpInfo($id_program, $id_review_type, $id_review, $id_image, $body = null)
    {
        $returnType = '';
        $request = $this->replaceProgramReviewTypeReviewImageRequest($id_program, $id_review_type, $id_review, $id_image, $body);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'replaceProgramReviewTypeReviewImage'
     *
     * @param  string $id_program Program UUID (required)
     * @param  string $id_review_type Review owner type (required)
     * @param  string $id_review Review identifier as UUID (required)
     * @param  string $id_image Image identifier in SHA1-Hash format derived from path (required)
     * @param  \Softonic\CatalogApiSdk\Client\Model\ProgramReviewTypeReviewImage $body (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function replaceProgramReviewTypeReviewImageRequest($id_program, $id_review_type, $id_review, $id_image, $body = null)
    {
        // verify the required parameter 'id_program' is set
        if ($id_program === null) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id_program when calling replaceProgramReviewTypeReviewImage'
            );
        }
        if (strlen($id_program) > 36) {
            throw new \InvalidArgumentException('invalid length for "$id_program" when calling ProgramsReviewTypesReviewsImagesApi.replaceProgramReviewTypeReviewImage, must be smaller than or equal to 36.');
        }
        if (strlen($id_program) < 36) {
            throw new \InvalidArgumentException('invalid length for "$id_program" when calling ProgramsReviewTypesReviewsImagesApi.replaceProgramReviewTypeReviewImage, must be bigger than or equal to 36.');
        }

        // verify the required parameter 'id_review_type' is set
        if ($id_review_type === null) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id_review_type when calling replaceProgramReviewTypeReviewImage'
            );
        }
        // verify the required parameter 'id_review' is set
        if ($id_review === null) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id_review when calling replaceProgramReviewTypeReviewImage'
            );
        }
        if (strlen($id_review) > 36) {
            throw new \InvalidArgumentException('invalid length for "$id_review" when calling ProgramsReviewTypesReviewsImagesApi.replaceProgramReviewTypeReviewImage, must be smaller than or equal to 36.');
        }
        if (strlen($id_review) < 36) {
            throw new \InvalidArgumentException('invalid length for "$id_review" when calling ProgramsReviewTypesReviewsImagesApi.replaceProgramReviewTypeReviewImage, must be bigger than or equal to 36.');
        }

        // verify the required parameter 'id_image' is set
        if ($id_image === null) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id_image when calling replaceProgramReviewTypeReviewImage'
            );
        }
        if (strlen($id_image) > 40) {
            throw new \InvalidArgumentException('invalid length for "$id_image" when calling ProgramsReviewTypesReviewsImagesApi.replaceProgramReviewTypeReviewImage, must be smaller than or equal to 40.');
        }
        if (strlen($id_image) < 40) {
            throw new \InvalidArgumentException('invalid length for "$id_image" when calling ProgramsReviewTypesReviewsImagesApi.replaceProgramReviewTypeReviewImage, must be bigger than or equal to 40.');
        }


        $resourcePath = '/programs/{id_program}/review-types/{id_review_type}/reviews/{id_review}/images/{id_image}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // path params
        if ($id_program !== null) {
            $resourcePath = str_replace(
                '{' . 'id_program' . '}',
                ObjectSerializer::toPathValue($id_program),
                $resourcePath
            );
        }
        // path params
        if ($id_review_type !== null) {
            $resourcePath = str_replace(
                '{' . 'id_review_type' . '}',
                ObjectSerializer::toPathValue($id_review_type),
                $resourcePath
            );
        }
        // path params
        if ($id_review !== null) {
            $resourcePath = str_replace(
                '{' . 'id_review' . '}',
                ObjectSerializer::toPathValue($id_review),
                $resourcePath
            );
        }
        // path params
        if ($id_image !== null) {
            $resourcePath = str_replace(
                '{' . 'id_image' . '}',
                ObjectSerializer::toPathValue($id_image),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;
        if (isset($body)) {
            $_tempBody = $body;
        }

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }
        // this endpoint requires OAuth (access token)
        if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }
        // this endpoint requires OAuth (access token)
        if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }
        // this endpoint requires OAuth (access token)
        if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'PUT',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation updateProgramReviewTypeReviewImage
     *
     * Partially updates a ProgramReviewTypeReviewImage
     *
     * @param  string $id_program Program UUID (required)
     * @param  string $id_review_type Review owner type (required)
     * @param  string $id_review Review identifier as UUID (required)
     * @param  string $id_image Image identifier in SHA1-Hash format derived from path (required)
     * @param  \Softonic\CatalogApiSdk\Client\Model\ProgramReviewTypeReviewImage $body body (optional)
     *
     * @throws \Softonic\CatalogApiSdk\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return void
     */
    public function updateProgramReviewTypeReviewImage($id_program, $id_review_type, $id_review, $id_image, $body = null)
    {
        $this->updateProgramReviewTypeReviewImageWithHttpInfo($id_program, $id_review_type, $id_review, $id_image, $body);
    }

    /**
     * Operation updateProgramReviewTypeReviewImageWithHttpInfo
     *
     * Partially updates a ProgramReviewTypeReviewImage
     *
     * @param  string $id_program Program UUID (required)
     * @param  string $id_review_type Review owner type (required)
     * @param  string $id_review Review identifier as UUID (required)
     * @param  string $id_image Image identifier in SHA1-Hash format derived from path (required)
     * @param  \Softonic\CatalogApiSdk\Client\Model\ProgramReviewTypeReviewImage $body (optional)
     *
     * @throws \Softonic\CatalogApiSdk\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function updateProgramReviewTypeReviewImageWithHttpInfo($id_program, $id_review_type, $id_review, $id_image, $body = null)
    {
        $returnType = '';
        $request = $this->updateProgramReviewTypeReviewImageRequest($id_program, $id_review_type, $id_review, $id_image, $body);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
            throw $e;
        }
    }

    /**
     * Operation updateProgramReviewTypeReviewImageAsync
     *
     * Partially updates a ProgramReviewTypeReviewImage
     *
     * @param  string $id_program Program UUID (required)
     * @param  string $id_review_type Review owner type (required)
     * @param  string $id_review Review identifier as UUID (required)
     * @param  string $id_image Image identifier in SHA1-Hash format derived from path (required)
     * @param  \Softonic\CatalogApiSdk\Client\Model\ProgramReviewTypeReviewImage $body (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function updateProgramReviewTypeReviewImageAsync($id_program, $id_review_type, $id_review, $id_image, $body = null)
    {
        return $this->updateProgramReviewTypeReviewImageAsyncWithHttpInfo($id_program, $id_review_type, $id_review, $id_image, $body)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation updateProgramReviewTypeReviewImageAsyncWithHttpInfo
     *
     * Partially updates a ProgramReviewTypeReviewImage
     *
     * @param  string $id_program Program UUID (required)
     * @param  string $id_review_type Review owner type (required)
     * @param  string $id_review Review identifier as UUID (required)
     * @param  string $id_image Image identifier in SHA1-Hash format derived from path (required)
     * @param  \Softonic\CatalogApiSdk\Client\Model\ProgramReviewTypeReviewImage $body (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function updateProgramReviewTypeReviewImageAsyncWithHttpInfo($id_program, $id_review_type, $id_review, $id_image, $body = null)
    {
        $returnType = '';
        $request = $this->updateProgramReviewTypeReviewImageRequest($id_program, $id_review_type, $id_review, $id_image, $body);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'updateProgramReviewTypeReviewImage'
     *
     * @param  string $id_program Program UUID (required)
     * @param  string $id_review_type Review owner type (required)
     * @param  string $id_review Review identifier as UUID (required)
     * @param  string $id_image Image identifier in SHA1-Hash format derived from path (required)
     * @param  \Softonic\CatalogApiSdk\Client\Model\ProgramReviewTypeReviewImage $body (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function updateProgramReviewTypeReviewImageRequest($id_program, $id_review_type, $id_review, $id_image, $body = null)
    {
        // verify the required parameter 'id_program' is set
        if ($id_program === null) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id_program when calling updateProgramReviewTypeReviewImage'
            );
        }
        if (strlen($id_program) > 36) {
            throw new \InvalidArgumentException('invalid length for "$id_program" when calling ProgramsReviewTypesReviewsImagesApi.updateProgramReviewTypeReviewImage, must be smaller than or equal to 36.');
        }
        if (strlen($id_program) < 36) {
            throw new \InvalidArgumentException('invalid length for "$id_program" when calling ProgramsReviewTypesReviewsImagesApi.updateProgramReviewTypeReviewImage, must be bigger than or equal to 36.');
        }

        // verify the required parameter 'id_review_type' is set
        if ($id_review_type === null) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id_review_type when calling updateProgramReviewTypeReviewImage'
            );
        }
        // verify the required parameter 'id_review' is set
        if ($id_review === null) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id_review when calling updateProgramReviewTypeReviewImage'
            );
        }
        if (strlen($id_review) > 36) {
            throw new \InvalidArgumentException('invalid length for "$id_review" when calling ProgramsReviewTypesReviewsImagesApi.updateProgramReviewTypeReviewImage, must be smaller than or equal to 36.');
        }
        if (strlen($id_review) < 36) {
            throw new \InvalidArgumentException('invalid length for "$id_review" when calling ProgramsReviewTypesReviewsImagesApi.updateProgramReviewTypeReviewImage, must be bigger than or equal to 36.');
        }

        // verify the required parameter 'id_image' is set
        if ($id_image === null) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id_image when calling updateProgramReviewTypeReviewImage'
            );
        }
        if (strlen($id_image) > 40) {
            throw new \InvalidArgumentException('invalid length for "$id_image" when calling ProgramsReviewTypesReviewsImagesApi.updateProgramReviewTypeReviewImage, must be smaller than or equal to 40.');
        }
        if (strlen($id_image) < 40) {
            throw new \InvalidArgumentException('invalid length for "$id_image" when calling ProgramsReviewTypesReviewsImagesApi.updateProgramReviewTypeReviewImage, must be bigger than or equal to 40.');
        }


        $resourcePath = '/programs/{id_program}/review-types/{id_review_type}/reviews/{id_review}/images/{id_image}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // path params
        if ($id_program !== null) {
            $resourcePath = str_replace(
                '{' . 'id_program' . '}',
                ObjectSerializer::toPathValue($id_program),
                $resourcePath
            );
        }
        // path params
        if ($id_review_type !== null) {
            $resourcePath = str_replace(
                '{' . 'id_review_type' . '}',
                ObjectSerializer::toPathValue($id_review_type),
                $resourcePath
            );
        }
        // path params
        if ($id_review !== null) {
            $resourcePath = str_replace(
                '{' . 'id_review' . '}',
                ObjectSerializer::toPathValue($id_review),
                $resourcePath
            );
        }
        // path params
        if ($id_image !== null) {
            $resourcePath = str_replace(
                '{' . 'id_image' . '}',
                ObjectSerializer::toPathValue($id_image),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;
        if (isset($body)) {
            $_tempBody = $body;
        }

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }
        // this endpoint requires OAuth (access token)
        if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }
        // this endpoint requires OAuth (access token)
        if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }
        // this endpoint requires OAuth (access token)
        if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'PATCH',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
