<?php
/**
 * ProgramsPlatformsSourcesApi
 * PHP version 5
 *
 * @category Class
 * @package  Softonic\CatalogApiSdk
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Catalog API
 *
 * API that allows to manage the programs catalog of Softonic
 *
 * OpenAPI spec version: 2.0.377-2222
 * Contact: team.platform@softonic.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Softonic\CatalogApiSdk\Client\Api;

use \Softonic\CatalogApiSdk\ApiClient;
use \Softonic\CatalogApiSdk\ApiException;
use \Softonic\CatalogApiSdk\Configuration;
use \Softonic\CatalogApiSdk\ObjectSerializer;

/**
 * ProgramsPlatformsSourcesApi Class Doc Comment
 *
 * @category Class
 * @package  Softonic\CatalogApiSdk
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ProgramsPlatformsSourcesApi
{
    /**
     * API Client
     *
     * @var \Softonic\CatalogApiSdk\ApiClient instance of the ApiClient
     */
    protected $apiClient;

    /**
     * Constructor
     *
     * @param \Softonic\CatalogApiSdk\ApiClient|null $apiClient The api client to use
     */
    public function __construct(\Softonic\CatalogApiSdk\ApiClient $apiClient = null)
    {
        if ($apiClient === null) {
            $apiClient = new ApiClient();
        }

        $this->apiClient = $apiClient;
    }

    /**
     * Get API client
     *
     * @return \Softonic\CatalogApiSdk\ApiClient get the API client
     */
    public function getApiClient()
    {
        return $this->apiClient;
    }

    /**
     * Set the API client
     *
     * @param \Softonic\CatalogApiSdk\ApiClient $apiClient set the API client
     *
     * @return ProgramsPlatformsSourcesApi
     */
    public function setApiClient(\Softonic\CatalogApiSdk\ApiClient $apiClient)
    {
        $this->apiClient = $apiClient;
        return $this;
    }

    /**
     * Operation createProgramPlatformSource
     *
     * Creates a new ProgramPlatformSource
     *
     * @param string $id_program Program UUID (required)
     * @param string $id_platform Platform identifier (required)
     * @param \Softonic\CatalogApiSdk\Client\Model\ProgramPlatformSource $body  (optional)
     * @throws \Softonic\CatalogApiSdk\ApiException on non-2xx response
     * @return void
     */
    public function createProgramPlatformSource($id_program, $id_platform, $body = null)
    {
        list($response) = $this->createProgramPlatformSourceWithHttpInfo($id_program, $id_platform, $body);
        return $response;
    }

    /**
     * Operation createProgramPlatformSourceWithHttpInfo
     *
     * Creates a new ProgramPlatformSource
     *
     * @param string $id_program Program UUID (required)
     * @param string $id_platform Platform identifier (required)
     * @param \Softonic\CatalogApiSdk\Client\Model\ProgramPlatformSource $body  (optional)
     * @throws \Softonic\CatalogApiSdk\ApiException on non-2xx response
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function createProgramPlatformSourceWithHttpInfo($id_program, $id_platform, $body = null)
    {
        // verify the required parameter 'id_program' is set
        if ($id_program === null) {
            throw new \InvalidArgumentException('Missing the required parameter $id_program when calling createProgramPlatformSource');
        }
        if ((strlen($id_program) > 36)) {
            throw new \InvalidArgumentException('invalid length for "$id_program" when calling ProgramsPlatformsSourcesApi.createProgramPlatformSource, must be smaller than or equal to 36.');
        }
        if ((strlen($id_program) < 36)) {
            throw new \InvalidArgumentException('invalid length for "$id_program" when calling ProgramsPlatformsSourcesApi.createProgramPlatformSource, must be bigger than or equal to 36.');
        }

        // verify the required parameter 'id_platform' is set
        if ($id_platform === null) {
            throw new \InvalidArgumentException('Missing the required parameter $id_platform when calling createProgramPlatformSource');
        }
        if ((strlen($id_platform) > 20)) {
            throw new \InvalidArgumentException('invalid length for "$id_platform" when calling ProgramsPlatformsSourcesApi.createProgramPlatformSource, must be smaller than or equal to 20.');
        }
        if ((strlen($id_platform) < 1)) {
            throw new \InvalidArgumentException('invalid length for "$id_platform" when calling ProgramsPlatformsSourcesApi.createProgramPlatformSource, must be bigger than or equal to 1.');
        }

        // parse inputs
        $resourcePath = "/programs/{id_program}/platforms/{id_platform}/sources";
        $httpBody = '';
        $queryParams = [];
        $headerParams = [];
        $formParams = [];
        $_header_accept = $this->apiClient->selectHeaderAccept(['application/json']);
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = $this->apiClient->selectHeaderContentType(['application/json']);

        // path params
        if ($id_program !== null) {
            $resourcePath = str_replace(
                "{" . "id_program" . "}",
                $this->apiClient->getSerializer()->toPathValue($id_program),
                $resourcePath
            );
        }
        // path params
        if ($id_platform !== null) {
            $resourcePath = str_replace(
                "{" . "id_platform" . "}",
                $this->apiClient->getSerializer()->toPathValue($id_platform),
                $resourcePath
            );
        }
        // body params
        $_tempBody = null;
        if (isset($body)) {
            $_tempBody = $body;
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        // this endpoint requires OAuth (access token)
        if (strlen($this->apiClient->getConfig()->getAccessToken()) !== 0) {
            $headerParams['Authorization'] = 'Bearer ' . $this->apiClient->getConfig()->getAccessToken();
        }
        // this endpoint requires OAuth (access token)
        if (strlen($this->apiClient->getConfig()->getAccessToken()) !== 0) {
            $headerParams['Authorization'] = 'Bearer ' . $this->apiClient->getConfig()->getAccessToken();
        }
        // this endpoint requires OAuth (access token)
        if (strlen($this->apiClient->getConfig()->getAccessToken()) !== 0) {
            $headerParams['Authorization'] = 'Bearer ' . $this->apiClient->getConfig()->getAccessToken();
        }
        // this endpoint requires OAuth (access token)
        if (strlen($this->apiClient->getConfig()->getAccessToken()) !== 0) {
            $headerParams['Authorization'] = 'Bearer ' . $this->apiClient->getConfig()->getAccessToken();
        }
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath,
                'POST',
                $queryParams,
                $httpBody,
                $headerParams,
                null,
                '/programs/{id_program}/platforms/{id_platform}/sources'
            );

            return [null, $statusCode, $httpHeader];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }

            throw $e;
        }
    }

    /**
     * Operation deleteProgramPlatformSource
     *
     * Deletes a ProgramPlatformSource
     *
     * @param string $id_program Program UUID (required)
     * @param string $id_platform Platform identifier (required)
     * @param string $id_source Source identifier (required)
     * @throws \Softonic\CatalogApiSdk\ApiException on non-2xx response
     * @return void
     */
    public function deleteProgramPlatformSource($id_program, $id_platform, $id_source)
    {
        list($response) = $this->deleteProgramPlatformSourceWithHttpInfo($id_program, $id_platform, $id_source);
        return $response;
    }

    /**
     * Operation deleteProgramPlatformSourceWithHttpInfo
     *
     * Deletes a ProgramPlatformSource
     *
     * @param string $id_program Program UUID (required)
     * @param string $id_platform Platform identifier (required)
     * @param string $id_source Source identifier (required)
     * @throws \Softonic\CatalogApiSdk\ApiException on non-2xx response
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function deleteProgramPlatformSourceWithHttpInfo($id_program, $id_platform, $id_source)
    {
        // verify the required parameter 'id_program' is set
        if ($id_program === null) {
            throw new \InvalidArgumentException('Missing the required parameter $id_program when calling deleteProgramPlatformSource');
        }
        if ((strlen($id_program) > 36)) {
            throw new \InvalidArgumentException('invalid length for "$id_program" when calling ProgramsPlatformsSourcesApi.deleteProgramPlatformSource, must be smaller than or equal to 36.');
        }
        if ((strlen($id_program) < 36)) {
            throw new \InvalidArgumentException('invalid length for "$id_program" when calling ProgramsPlatformsSourcesApi.deleteProgramPlatformSource, must be bigger than or equal to 36.');
        }

        // verify the required parameter 'id_platform' is set
        if ($id_platform === null) {
            throw new \InvalidArgumentException('Missing the required parameter $id_platform when calling deleteProgramPlatformSource');
        }
        if ((strlen($id_platform) > 20)) {
            throw new \InvalidArgumentException('invalid length for "$id_platform" when calling ProgramsPlatformsSourcesApi.deleteProgramPlatformSource, must be smaller than or equal to 20.');
        }
        if ((strlen($id_platform) < 1)) {
            throw new \InvalidArgumentException('invalid length for "$id_platform" when calling ProgramsPlatformsSourcesApi.deleteProgramPlatformSource, must be bigger than or equal to 1.');
        }

        // verify the required parameter 'id_source' is set
        if ($id_source === null) {
            throw new \InvalidArgumentException('Missing the required parameter $id_source when calling deleteProgramPlatformSource');
        }
        if ((strlen($id_source) > 20)) {
            throw new \InvalidArgumentException('invalid length for "$id_source" when calling ProgramsPlatformsSourcesApi.deleteProgramPlatformSource, must be smaller than or equal to 20.');
        }
        if ((strlen($id_source) < 1)) {
            throw new \InvalidArgumentException('invalid length for "$id_source" when calling ProgramsPlatformsSourcesApi.deleteProgramPlatformSource, must be bigger than or equal to 1.');
        }

        // parse inputs
        $resourcePath = "/programs/{id_program}/platforms/{id_platform}/sources/{id_source}";
        $httpBody = '';
        $queryParams = [];
        $headerParams = [];
        $formParams = [];
        $_header_accept = $this->apiClient->selectHeaderAccept(['application/json']);
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = $this->apiClient->selectHeaderContentType(['application/json']);

        // path params
        if ($id_program !== null) {
            $resourcePath = str_replace(
                "{" . "id_program" . "}",
                $this->apiClient->getSerializer()->toPathValue($id_program),
                $resourcePath
            );
        }
        // path params
        if ($id_platform !== null) {
            $resourcePath = str_replace(
                "{" . "id_platform" . "}",
                $this->apiClient->getSerializer()->toPathValue($id_platform),
                $resourcePath
            );
        }
        // path params
        if ($id_source !== null) {
            $resourcePath = str_replace(
                "{" . "id_source" . "}",
                $this->apiClient->getSerializer()->toPathValue($id_source),
                $resourcePath
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        // this endpoint requires OAuth (access token)
        if (strlen($this->apiClient->getConfig()->getAccessToken()) !== 0) {
            $headerParams['Authorization'] = 'Bearer ' . $this->apiClient->getConfig()->getAccessToken();
        }
        // this endpoint requires OAuth (access token)
        if (strlen($this->apiClient->getConfig()->getAccessToken()) !== 0) {
            $headerParams['Authorization'] = 'Bearer ' . $this->apiClient->getConfig()->getAccessToken();
        }
        // this endpoint requires OAuth (access token)
        if (strlen($this->apiClient->getConfig()->getAccessToken()) !== 0) {
            $headerParams['Authorization'] = 'Bearer ' . $this->apiClient->getConfig()->getAccessToken();
        }
        // this endpoint requires OAuth (access token)
        if (strlen($this->apiClient->getConfig()->getAccessToken()) !== 0) {
            $headerParams['Authorization'] = 'Bearer ' . $this->apiClient->getConfig()->getAccessToken();
        }
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath,
                'DELETE',
                $queryParams,
                $httpBody,
                $headerParams,
                null,
                '/programs/{id_program}/platforms/{id_platform}/sources/{id_source}'
            );

            return [null, $statusCode, $httpHeader];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }

            throw $e;
        }
    }

    /**
     * Operation findProgramPlatformSource
     *
     * List of ProgramPlatformSources
     *
     * @param string $id_program Program UUID (required)
     * @param string $id_platform Platform identifier (required)
     * @throws \Softonic\CatalogApiSdk\ApiException on non-2xx response
     * @return \Softonic\CatalogApiSdk\Client\Model\ProgramPlatformSource[]
     */
    public function findProgramPlatformSource($id_program, $id_platform)
    {
        list($response) = $this->findProgramPlatformSourceWithHttpInfo($id_program, $id_platform);
        return $response;
    }

    /**
     * Operation findProgramPlatformSourceWithHttpInfo
     *
     * List of ProgramPlatformSources
     *
     * @param string $id_program Program UUID (required)
     * @param string $id_platform Platform identifier (required)
     * @throws \Softonic\CatalogApiSdk\ApiException on non-2xx response
     * @return array of \Softonic\CatalogApiSdk\Client\Model\ProgramPlatformSource[], HTTP status code, HTTP response headers (array of strings)
     */
    public function findProgramPlatformSourceWithHttpInfo($id_program, $id_platform)
    {
        // verify the required parameter 'id_program' is set
        if ($id_program === null) {
            throw new \InvalidArgumentException('Missing the required parameter $id_program when calling findProgramPlatformSource');
        }
        if ((strlen($id_program) > 36)) {
            throw new \InvalidArgumentException('invalid length for "$id_program" when calling ProgramsPlatformsSourcesApi.findProgramPlatformSource, must be smaller than or equal to 36.');
        }
        if ((strlen($id_program) < 36)) {
            throw new \InvalidArgumentException('invalid length for "$id_program" when calling ProgramsPlatformsSourcesApi.findProgramPlatformSource, must be bigger than or equal to 36.');
        }

        // verify the required parameter 'id_platform' is set
        if ($id_platform === null) {
            throw new \InvalidArgumentException('Missing the required parameter $id_platform when calling findProgramPlatformSource');
        }
        if ((strlen($id_platform) > 20)) {
            throw new \InvalidArgumentException('invalid length for "$id_platform" when calling ProgramsPlatformsSourcesApi.findProgramPlatformSource, must be smaller than or equal to 20.');
        }
        if ((strlen($id_platform) < 1)) {
            throw new \InvalidArgumentException('invalid length for "$id_platform" when calling ProgramsPlatformsSourcesApi.findProgramPlatformSource, must be bigger than or equal to 1.');
        }

        // parse inputs
        $resourcePath = "/programs/{id_program}/platforms/{id_platform}/sources";
        $httpBody = '';
        $queryParams = [];
        $headerParams = [];
        $formParams = [];
        $_header_accept = $this->apiClient->selectHeaderAccept(['application/json']);
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = $this->apiClient->selectHeaderContentType(['application/json']);

        // path params
        if ($id_program !== null) {
            $resourcePath = str_replace(
                "{" . "id_program" . "}",
                $this->apiClient->getSerializer()->toPathValue($id_program),
                $resourcePath
            );
        }
        // path params
        if ($id_platform !== null) {
            $resourcePath = str_replace(
                "{" . "id_platform" . "}",
                $this->apiClient->getSerializer()->toPathValue($id_platform),
                $resourcePath
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        // this endpoint requires OAuth (access token)
        if (strlen($this->apiClient->getConfig()->getAccessToken()) !== 0) {
            $headerParams['Authorization'] = 'Bearer ' . $this->apiClient->getConfig()->getAccessToken();
        }
        // this endpoint requires OAuth (access token)
        if (strlen($this->apiClient->getConfig()->getAccessToken()) !== 0) {
            $headerParams['Authorization'] = 'Bearer ' . $this->apiClient->getConfig()->getAccessToken();
        }
        // this endpoint requires OAuth (access token)
        if (strlen($this->apiClient->getConfig()->getAccessToken()) !== 0) {
            $headerParams['Authorization'] = 'Bearer ' . $this->apiClient->getConfig()->getAccessToken();
        }
        // this endpoint requires OAuth (access token)
        if (strlen($this->apiClient->getConfig()->getAccessToken()) !== 0) {
            $headerParams['Authorization'] = 'Bearer ' . $this->apiClient->getConfig()->getAccessToken();
        }
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath,
                'GET',
                $queryParams,
                $httpBody,
                $headerParams,
                '\Softonic\CatalogApiSdk\Client\Model\ProgramPlatformSource[]',
                '/programs/{id_program}/platforms/{id_platform}/sources'
            );

            return [$this->apiClient->getSerializer()->deserialize($response, '\Softonic\CatalogApiSdk\Client\Model\ProgramPlatformSource[]', $httpHeader), $statusCode, $httpHeader];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\Softonic\CatalogApiSdk\Client\Model\ProgramPlatformSource[]', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
            }

            throw $e;
        }
    }

    /**
     * Operation readProgramPlatformSource
     *
     * Fetches a single ProgramPlatformSource
     *
     * @param string $id_program Program UUID (required)
     * @param string $id_platform Platform identifier (required)
     * @param string $id_source Source identifier (required)
     * @throws \Softonic\CatalogApiSdk\ApiException on non-2xx response
     * @return \Softonic\CatalogApiSdk\Client\Model\ProgramPlatformSource
     */
    public function readProgramPlatformSource($id_program, $id_platform, $id_source)
    {
        list($response) = $this->readProgramPlatformSourceWithHttpInfo($id_program, $id_platform, $id_source);
        return $response;
    }

    /**
     * Operation readProgramPlatformSourceWithHttpInfo
     *
     * Fetches a single ProgramPlatformSource
     *
     * @param string $id_program Program UUID (required)
     * @param string $id_platform Platform identifier (required)
     * @param string $id_source Source identifier (required)
     * @throws \Softonic\CatalogApiSdk\ApiException on non-2xx response
     * @return array of \Softonic\CatalogApiSdk\Client\Model\ProgramPlatformSource, HTTP status code, HTTP response headers (array of strings)
     */
    public function readProgramPlatformSourceWithHttpInfo($id_program, $id_platform, $id_source)
    {
        // verify the required parameter 'id_program' is set
        if ($id_program === null) {
            throw new \InvalidArgumentException('Missing the required parameter $id_program when calling readProgramPlatformSource');
        }
        if ((strlen($id_program) > 36)) {
            throw new \InvalidArgumentException('invalid length for "$id_program" when calling ProgramsPlatformsSourcesApi.readProgramPlatformSource, must be smaller than or equal to 36.');
        }
        if ((strlen($id_program) < 36)) {
            throw new \InvalidArgumentException('invalid length for "$id_program" when calling ProgramsPlatformsSourcesApi.readProgramPlatformSource, must be bigger than or equal to 36.');
        }

        // verify the required parameter 'id_platform' is set
        if ($id_platform === null) {
            throw new \InvalidArgumentException('Missing the required parameter $id_platform when calling readProgramPlatformSource');
        }
        if ((strlen($id_platform) > 20)) {
            throw new \InvalidArgumentException('invalid length for "$id_platform" when calling ProgramsPlatformsSourcesApi.readProgramPlatformSource, must be smaller than or equal to 20.');
        }
        if ((strlen($id_platform) < 1)) {
            throw new \InvalidArgumentException('invalid length for "$id_platform" when calling ProgramsPlatformsSourcesApi.readProgramPlatformSource, must be bigger than or equal to 1.');
        }

        // verify the required parameter 'id_source' is set
        if ($id_source === null) {
            throw new \InvalidArgumentException('Missing the required parameter $id_source when calling readProgramPlatformSource');
        }
        if ((strlen($id_source) > 20)) {
            throw new \InvalidArgumentException('invalid length for "$id_source" when calling ProgramsPlatformsSourcesApi.readProgramPlatformSource, must be smaller than or equal to 20.');
        }
        if ((strlen($id_source) < 1)) {
            throw new \InvalidArgumentException('invalid length for "$id_source" when calling ProgramsPlatformsSourcesApi.readProgramPlatformSource, must be bigger than or equal to 1.');
        }

        // parse inputs
        $resourcePath = "/programs/{id_program}/platforms/{id_platform}/sources/{id_source}";
        $httpBody = '';
        $queryParams = [];
        $headerParams = [];
        $formParams = [];
        $_header_accept = $this->apiClient->selectHeaderAccept(['application/json']);
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = $this->apiClient->selectHeaderContentType(['application/json']);

        // path params
        if ($id_program !== null) {
            $resourcePath = str_replace(
                "{" . "id_program" . "}",
                $this->apiClient->getSerializer()->toPathValue($id_program),
                $resourcePath
            );
        }
        // path params
        if ($id_platform !== null) {
            $resourcePath = str_replace(
                "{" . "id_platform" . "}",
                $this->apiClient->getSerializer()->toPathValue($id_platform),
                $resourcePath
            );
        }
        // path params
        if ($id_source !== null) {
            $resourcePath = str_replace(
                "{" . "id_source" . "}",
                $this->apiClient->getSerializer()->toPathValue($id_source),
                $resourcePath
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        // this endpoint requires OAuth (access token)
        if (strlen($this->apiClient->getConfig()->getAccessToken()) !== 0) {
            $headerParams['Authorization'] = 'Bearer ' . $this->apiClient->getConfig()->getAccessToken();
        }
        // this endpoint requires OAuth (access token)
        if (strlen($this->apiClient->getConfig()->getAccessToken()) !== 0) {
            $headerParams['Authorization'] = 'Bearer ' . $this->apiClient->getConfig()->getAccessToken();
        }
        // this endpoint requires OAuth (access token)
        if (strlen($this->apiClient->getConfig()->getAccessToken()) !== 0) {
            $headerParams['Authorization'] = 'Bearer ' . $this->apiClient->getConfig()->getAccessToken();
        }
        // this endpoint requires OAuth (access token)
        if (strlen($this->apiClient->getConfig()->getAccessToken()) !== 0) {
            $headerParams['Authorization'] = 'Bearer ' . $this->apiClient->getConfig()->getAccessToken();
        }
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath,
                'GET',
                $queryParams,
                $httpBody,
                $headerParams,
                '\Softonic\CatalogApiSdk\Client\Model\ProgramPlatformSource',
                '/programs/{id_program}/platforms/{id_platform}/sources/{id_source}'
            );

            return [$this->apiClient->getSerializer()->deserialize($response, '\Softonic\CatalogApiSdk\Client\Model\ProgramPlatformSource', $httpHeader), $statusCode, $httpHeader];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\Softonic\CatalogApiSdk\Client\Model\ProgramPlatformSource', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
            }

            throw $e;
        }
    }

    /**
     * Operation replaceProgramPlatformSource
     *
     * Entirely replaces a ProgramPlatformSource
     *
     * @param string $id_program Program UUID (required)
     * @param string $id_platform Platform identifier (required)
     * @param string $id_source Source identifier (required)
     * @param \Softonic\CatalogApiSdk\Client\Model\ProgramPlatformSource $body  (optional)
     * @throws \Softonic\CatalogApiSdk\ApiException on non-2xx response
     * @return void
     */
    public function replaceProgramPlatformSource($id_program, $id_platform, $id_source, $body = null)
    {
        list($response) = $this->replaceProgramPlatformSourceWithHttpInfo($id_program, $id_platform, $id_source, $body);
        return $response;
    }

    /**
     * Operation replaceProgramPlatformSourceWithHttpInfo
     *
     * Entirely replaces a ProgramPlatformSource
     *
     * @param string $id_program Program UUID (required)
     * @param string $id_platform Platform identifier (required)
     * @param string $id_source Source identifier (required)
     * @param \Softonic\CatalogApiSdk\Client\Model\ProgramPlatformSource $body  (optional)
     * @throws \Softonic\CatalogApiSdk\ApiException on non-2xx response
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function replaceProgramPlatformSourceWithHttpInfo($id_program, $id_platform, $id_source, $body = null)
    {
        // verify the required parameter 'id_program' is set
        if ($id_program === null) {
            throw new \InvalidArgumentException('Missing the required parameter $id_program when calling replaceProgramPlatformSource');
        }
        if ((strlen($id_program) > 36)) {
            throw new \InvalidArgumentException('invalid length for "$id_program" when calling ProgramsPlatformsSourcesApi.replaceProgramPlatformSource, must be smaller than or equal to 36.');
        }
        if ((strlen($id_program) < 36)) {
            throw new \InvalidArgumentException('invalid length for "$id_program" when calling ProgramsPlatformsSourcesApi.replaceProgramPlatformSource, must be bigger than or equal to 36.');
        }

        // verify the required parameter 'id_platform' is set
        if ($id_platform === null) {
            throw new \InvalidArgumentException('Missing the required parameter $id_platform when calling replaceProgramPlatformSource');
        }
        if ((strlen($id_platform) > 20)) {
            throw new \InvalidArgumentException('invalid length for "$id_platform" when calling ProgramsPlatformsSourcesApi.replaceProgramPlatformSource, must be smaller than or equal to 20.');
        }
        if ((strlen($id_platform) < 1)) {
            throw new \InvalidArgumentException('invalid length for "$id_platform" when calling ProgramsPlatformsSourcesApi.replaceProgramPlatformSource, must be bigger than or equal to 1.');
        }

        // verify the required parameter 'id_source' is set
        if ($id_source === null) {
            throw new \InvalidArgumentException('Missing the required parameter $id_source when calling replaceProgramPlatformSource');
        }
        if ((strlen($id_source) > 20)) {
            throw new \InvalidArgumentException('invalid length for "$id_source" when calling ProgramsPlatformsSourcesApi.replaceProgramPlatformSource, must be smaller than or equal to 20.');
        }
        if ((strlen($id_source) < 1)) {
            throw new \InvalidArgumentException('invalid length for "$id_source" when calling ProgramsPlatformsSourcesApi.replaceProgramPlatformSource, must be bigger than or equal to 1.');
        }

        // parse inputs
        $resourcePath = "/programs/{id_program}/platforms/{id_platform}/sources/{id_source}";
        $httpBody = '';
        $queryParams = [];
        $headerParams = [];
        $formParams = [];
        $_header_accept = $this->apiClient->selectHeaderAccept(['application/json']);
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = $this->apiClient->selectHeaderContentType(['application/json']);

        // path params
        if ($id_program !== null) {
            $resourcePath = str_replace(
                "{" . "id_program" . "}",
                $this->apiClient->getSerializer()->toPathValue($id_program),
                $resourcePath
            );
        }
        // path params
        if ($id_platform !== null) {
            $resourcePath = str_replace(
                "{" . "id_platform" . "}",
                $this->apiClient->getSerializer()->toPathValue($id_platform),
                $resourcePath
            );
        }
        // path params
        if ($id_source !== null) {
            $resourcePath = str_replace(
                "{" . "id_source" . "}",
                $this->apiClient->getSerializer()->toPathValue($id_source),
                $resourcePath
            );
        }
        // body params
        $_tempBody = null;
        if (isset($body)) {
            $_tempBody = $body;
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        // this endpoint requires OAuth (access token)
        if (strlen($this->apiClient->getConfig()->getAccessToken()) !== 0) {
            $headerParams['Authorization'] = 'Bearer ' . $this->apiClient->getConfig()->getAccessToken();
        }
        // this endpoint requires OAuth (access token)
        if (strlen($this->apiClient->getConfig()->getAccessToken()) !== 0) {
            $headerParams['Authorization'] = 'Bearer ' . $this->apiClient->getConfig()->getAccessToken();
        }
        // this endpoint requires OAuth (access token)
        if (strlen($this->apiClient->getConfig()->getAccessToken()) !== 0) {
            $headerParams['Authorization'] = 'Bearer ' . $this->apiClient->getConfig()->getAccessToken();
        }
        // this endpoint requires OAuth (access token)
        if (strlen($this->apiClient->getConfig()->getAccessToken()) !== 0) {
            $headerParams['Authorization'] = 'Bearer ' . $this->apiClient->getConfig()->getAccessToken();
        }
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath,
                'PUT',
                $queryParams,
                $httpBody,
                $headerParams,
                null,
                '/programs/{id_program}/platforms/{id_platform}/sources/{id_source}'
            );

            return [null, $statusCode, $httpHeader];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }

            throw $e;
        }
    }

    /**
     * Operation updateProgramPlatformSource
     *
     * Partially updates a ProgramPlatformSource
     *
     * @param string $id_program Program UUID (required)
     * @param string $id_platform Platform identifier (required)
     * @param string $id_source Source identifier (required)
     * @param \Softonic\CatalogApiSdk\Client\Model\ProgramPlatformSource $body  (optional)
     * @throws \Softonic\CatalogApiSdk\ApiException on non-2xx response
     * @return void
     */
    public function updateProgramPlatformSource($id_program, $id_platform, $id_source, $body = null)
    {
        list($response) = $this->updateProgramPlatformSourceWithHttpInfo($id_program, $id_platform, $id_source, $body);
        return $response;
    }

    /**
     * Operation updateProgramPlatformSourceWithHttpInfo
     *
     * Partially updates a ProgramPlatformSource
     *
     * @param string $id_program Program UUID (required)
     * @param string $id_platform Platform identifier (required)
     * @param string $id_source Source identifier (required)
     * @param \Softonic\CatalogApiSdk\Client\Model\ProgramPlatformSource $body  (optional)
     * @throws \Softonic\CatalogApiSdk\ApiException on non-2xx response
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function updateProgramPlatformSourceWithHttpInfo($id_program, $id_platform, $id_source, $body = null)
    {
        // verify the required parameter 'id_program' is set
        if ($id_program === null) {
            throw new \InvalidArgumentException('Missing the required parameter $id_program when calling updateProgramPlatformSource');
        }
        if ((strlen($id_program) > 36)) {
            throw new \InvalidArgumentException('invalid length for "$id_program" when calling ProgramsPlatformsSourcesApi.updateProgramPlatformSource, must be smaller than or equal to 36.');
        }
        if ((strlen($id_program) < 36)) {
            throw new \InvalidArgumentException('invalid length for "$id_program" when calling ProgramsPlatformsSourcesApi.updateProgramPlatformSource, must be bigger than or equal to 36.');
        }

        // verify the required parameter 'id_platform' is set
        if ($id_platform === null) {
            throw new \InvalidArgumentException('Missing the required parameter $id_platform when calling updateProgramPlatformSource');
        }
        if ((strlen($id_platform) > 20)) {
            throw new \InvalidArgumentException('invalid length for "$id_platform" when calling ProgramsPlatformsSourcesApi.updateProgramPlatformSource, must be smaller than or equal to 20.');
        }
        if ((strlen($id_platform) < 1)) {
            throw new \InvalidArgumentException('invalid length for "$id_platform" when calling ProgramsPlatformsSourcesApi.updateProgramPlatformSource, must be bigger than or equal to 1.');
        }

        // verify the required parameter 'id_source' is set
        if ($id_source === null) {
            throw new \InvalidArgumentException('Missing the required parameter $id_source when calling updateProgramPlatformSource');
        }
        if ((strlen($id_source) > 20)) {
            throw new \InvalidArgumentException('invalid length for "$id_source" when calling ProgramsPlatformsSourcesApi.updateProgramPlatformSource, must be smaller than or equal to 20.');
        }
        if ((strlen($id_source) < 1)) {
            throw new \InvalidArgumentException('invalid length for "$id_source" when calling ProgramsPlatformsSourcesApi.updateProgramPlatformSource, must be bigger than or equal to 1.');
        }

        // parse inputs
        $resourcePath = "/programs/{id_program}/platforms/{id_platform}/sources/{id_source}";
        $httpBody = '';
        $queryParams = [];
        $headerParams = [];
        $formParams = [];
        $_header_accept = $this->apiClient->selectHeaderAccept(['application/json']);
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = $this->apiClient->selectHeaderContentType(['application/json']);

        // path params
        if ($id_program !== null) {
            $resourcePath = str_replace(
                "{" . "id_program" . "}",
                $this->apiClient->getSerializer()->toPathValue($id_program),
                $resourcePath
            );
        }
        // path params
        if ($id_platform !== null) {
            $resourcePath = str_replace(
                "{" . "id_platform" . "}",
                $this->apiClient->getSerializer()->toPathValue($id_platform),
                $resourcePath
            );
        }
        // path params
        if ($id_source !== null) {
            $resourcePath = str_replace(
                "{" . "id_source" . "}",
                $this->apiClient->getSerializer()->toPathValue($id_source),
                $resourcePath
            );
        }
        // body params
        $_tempBody = null;
        if (isset($body)) {
            $_tempBody = $body;
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        // this endpoint requires OAuth (access token)
        if (strlen($this->apiClient->getConfig()->getAccessToken()) !== 0) {
            $headerParams['Authorization'] = 'Bearer ' . $this->apiClient->getConfig()->getAccessToken();
        }
        // this endpoint requires OAuth (access token)
        if (strlen($this->apiClient->getConfig()->getAccessToken()) !== 0) {
            $headerParams['Authorization'] = 'Bearer ' . $this->apiClient->getConfig()->getAccessToken();
        }
        // this endpoint requires OAuth (access token)
        if (strlen($this->apiClient->getConfig()->getAccessToken()) !== 0) {
            $headerParams['Authorization'] = 'Bearer ' . $this->apiClient->getConfig()->getAccessToken();
        }
        // this endpoint requires OAuth (access token)
        if (strlen($this->apiClient->getConfig()->getAccessToken()) !== 0) {
            $headerParams['Authorization'] = 'Bearer ' . $this->apiClient->getConfig()->getAccessToken();
        }
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath,
                'PATCH',
                $queryParams,
                $httpBody,
                $headerParams,
                null,
                '/programs/{id_program}/platforms/{id_platform}/sources/{id_source}'
            );

            return [null, $statusCode, $httpHeader];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }

            throw $e;
        }
    }
}
