<?php
/**
 * ProgramPlatformReviewtypeTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Swagger Catalog API
 *
 * This API is the responsible to store all program related information.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: javier.eurrutia@softonic.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.8
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ProgramPlatformReviewtypeTest Class Doc Comment
 *
 * @category    Class
 * @description Program platform reviewtype model
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ProgramPlatformReviewtypeTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ProgramPlatformReviewtype"
     */
    public function testProgramPlatformReviewtype()
    {
    }

    /**
     * Test attribute "id_program"
     */
    public function testPropertyIdProgram()
    {
    }

    /**
     * Test attribute "id_platform"
     */
    public function testPropertyIdPlatform()
    {
    }

    /**
     * Test attribute "id_reviewtype"
     */
    public function testPropertyIdReviewtype()
    {
    }
}
