<?php
/**
 * ProgramsPlatformsVersionsLanguagesBinariesApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Softonic\CatalogApiSdk
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Swagger Catalog API
 *
 * This API is the responsible to store all program related information.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: javier.eurrutia@softonic.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.9
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Softonic\CatalogApiSdk;

use Softonic\CatalogApiSdk\Configuration;
use Softonic\CatalogApiSdk\ApiException;
use Softonic\CatalogApiSdk\ObjectSerializer;

/**
 * ProgramsPlatformsVersionsLanguagesBinariesApiTest Class Doc Comment
 *
 * @category Class
 * @package  Softonic\CatalogApiSdk
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ProgramsPlatformsVersionsLanguagesBinariesApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createProgramPlatformVersionLanguageBinary
     *
     * Creates a ProgramPlatformVersionLanguageBinary.
     *
     */
    public function testCreateProgramPlatformVersionLanguageBinary()
    {
    }

    /**
     * Test case for deleteProgramPlatformVersionLanguageBinary
     *
     * Deletes a ProgramPlatformVersionLanguageBinary.
     *
     */
    public function testDeleteProgramPlatformVersionLanguageBinary()
    {
    }

    /**
     * Test case for findProgramPlatformVersionLanguageBinary
     *
     * Gets a ProgramPlatformVersionLanguageBinary list.
     *
     */
    public function testFindProgramPlatformVersionLanguageBinary()
    {
    }

    /**
     * Test case for readProgramPlatformVersionLanguageBinary
     *
     * Fetches a single ProgramPlatformVersionLanguageBinary.
     *
     */
    public function testReadProgramPlatformVersionLanguageBinary()
    {
    }

    /**
     * Test case for replaceProgramPlatformVersionLanguageBinary
     *
     * Entirely replaces a ProgramPlatformVersionLanguageBinary.
     *
     */
    public function testReplaceProgramPlatformVersionLanguageBinary()
    {
    }
}
