<?php
/**
 * ProgramsPlatformsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Softonic\CatalogApiSdk
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Swagger Catalog API
 *
 * This API is the responsible to store all program related information.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: javier.eurrutia@softonic.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.9
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Softonic\CatalogApiSdk;

use Softonic\CatalogApiSdk\Configuration;
use Softonic\CatalogApiSdk\ApiException;
use Softonic\CatalogApiSdk\ObjectSerializer;

/**
 * ProgramsPlatformsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Softonic\CatalogApiSdk
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ProgramsPlatformsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createProgramPlatform
     *
     * Creates a ProgramPlatform.
     *
     */
    public function testCreateProgramPlatform()
    {
    }

    /**
     * Test case for deleteProgramPlatform
     *
     * Deletes a ProgramPlatform.
     *
     */
    public function testDeleteProgramPlatform()
    {
    }

    /**
     * Test case for findProgramPlatform
     *
     * Gets a ProgramPlatform list.
     *
     */
    public function testFindProgramPlatform()
    {
    }

    /**
     * Test case for readProgramPlatform
     *
     * Fetches a single ProgramPlatform.
     *
     */
    public function testReadProgramPlatform()
    {
    }

    /**
     * Test case for replaceProgramPlatform
     *
     * Entirely replaces a ProgramPlatform.
     *
     */
    public function testReplaceProgramPlatform()
    {
    }

    /**
     * Test case for updateProgramPlatform
     *
     * Partially updates a ProgramPlatform.
     *
     */
    public function testUpdateProgramPlatform()
    {
    }
}
