<?php
/**
 * ProgramsReviewTypesReviewsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Softonic\CatalogApiSdk
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Catalog API
 *
 * API that allows to manage the programs catalog of Softonic
 *
 * OpenAPI spec version: 2.0.99-904
 * Contact: team.platform@softonic.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Softonic\CatalogApiSdk\Api;

use \Softonic\CatalogApiSdk\Configuration;
use \Softonic\CatalogApiSdk\ApiClient;
use \Softonic\CatalogApiSdk\ApiException;
use \Softonic\CatalogApiSdk\ObjectSerializer;

/**
 * ProgramsReviewTypesReviewsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Softonic\CatalogApiSdk
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ProgramsReviewTypesReviewsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running each test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Clean up after running each test case
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test case for createProgramReviewTypeReview
     *
     * Creates a new ProgramReviewTypeReview.
     *
     */
    public function testCreateProgramReviewTypeReview()
    {

    }
    /**
     * Test case for deleteProgramReviewTypeReview
     *
     * Deletes a ProgramReviewTypeReview.
     *
     */
    public function testDeleteProgramReviewTypeReview()
    {

    }
    /**
     * Test case for findProgramReviewTypeReview
     *
     * List of ProgramReviewTypeReviews.
     *
     */
    public function testFindProgramReviewTypeReview()
    {

    }
    /**
     * Test case for readProgramReviewTypeReview
     *
     * Fetches a single ProgramReviewTypeReview.
     *
     */
    public function testReadProgramReviewTypeReview()
    {

    }
    /**
     * Test case for replaceProgramReviewTypeReview
     *
     * Entirely replaces a ProgramReviewTypeReview.
     *
     */
    public function testReplaceProgramReviewTypeReview()
    {

    }
    /**
     * Test case for updateProgramReviewTypeReview
     *
     * Partially updates a ProgramReviewTypeReview.
     *
     */
    public function testUpdateProgramReviewTypeReview()
    {

    }
}
