<?php
/**
 * ProgramsPlatformsLanguagesAliasesApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Softonic\CatalogApiSdk
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Swagger Catalog API
 *
 * This API is the responsible to store all program related information.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: javier.eurrutia@softonic.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.9
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Softonic\CatalogApiSdk;

use Softonic\CatalogApiSdk\Configuration;
use Softonic\CatalogApiSdk\ApiException;
use Softonic\CatalogApiSdk\ObjectSerializer;

/**
 * ProgramsPlatformsLanguagesAliasesApiTest Class Doc Comment
 *
 * @category Class
 * @package  Softonic\CatalogApiSdk
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ProgramsPlatformsLanguagesAliasesApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createProgramPlatformLanguageAlias
     *
     * Creates a ProgramPlatformLanguageAlias.
     *
     */
    public function testCreateProgramPlatformLanguageAlias()
    {
    }

    /**
     * Test case for deleteProgramPlatformLanguageAlias
     *
     * Deletes a ProgramPlatformLanguageAlias.
     *
     */
    public function testDeleteProgramPlatformLanguageAlias()
    {
    }

    /**
     * Test case for findProgramPlatformLanguageAlias
     *
     * Gets a ProgramPlatformLanguageAlias list.
     *
     */
    public function testFindProgramPlatformLanguageAlias()
    {
    }

    /**
     * Test case for readProgramPlatformLanguageAlias
     *
     * Fetches a single ProgramPlatformLanguageAlias.
     *
     */
    public function testReadProgramPlatformLanguageAlias()
    {
    }

    /**
     * Test case for replaceProgramPlatformLanguageAlias
     *
     * Entirely replaces a ProgramPlatformLanguageAlias.
     *
     */
    public function testReplaceProgramPlatformLanguageAlias()
    {
    }
}
